boards:
  main:
    '9': '§d§m╴ ╴§b§m'
    '8': '§6⋅ §fПлюшки§7 §a/gadget'
    '7': '§6⋅ §fСемья§7 §a/family'
    '6': '§6⋅ §fПитомцы§7 §a/pet'
    '5': '§6⋅ §fМеню варпов§7 §a/warp'
    '4': '§6ꉩ §bЛегендарное§7 §e/legacy'
    '3': '§d§m §b§m'
    '2': '§d'
    '1': '§c⚠ §eДонат§7 §b/donate'
  donate:
    '15': '§d§m ╴§b§m'
    '14': '§6⋅ §b§lNEW §cКонсоль §7→ §a999 §6Руб'
    '13': '§6⋅ §cВладелец §7→ §a499 §6Руб'
    '12': '§6⋅ §cСоздатель §7→ §a399 §6Руб'
    '11': '§6⋅ §cАнтиГриф §7→ §a299 §6Руб'
    '10': '§6⋅ §cUltra §7→ §a199 §6Руб'
    '9': '§6⋅ §cLord §7→ §a90 §6Руб'
    '8': '§6⋅ §cАдмин §7→ §a49 §6Руб'
    '7': '§6⋅ §cКреатив §7→ §a29 §6Руб'
    '6': '§6⋅ §cPremium §7→ §a19 §6Руб'
    '5': '§6⋅ §cViP §7→ §a9 §6Руб'
    '4': '§d§m §b§m'
    '3': '§6'
    '2': '§3⚠ §eВсё о донате§8: §b/donate'
ranks:
  '1': §f[§7Новичок§f]
  '2': §f[§aБоец§f]
  '3': §f[§aфицер§f]
  '4': §f[§aКомандир§f]
  '5': §f[§eГенерал§f]
  '6': §f[§eЛегенда§f]
  '7': §f[§cМодератор§f]
  '8': §f[§cЗаместитель§f]
  '9': §f[§4Глава§f]
